---
- name: create rados gateway directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ ceph_uid if containerized_deployment else 'ceph' }}"
    group: "{{ ceph_uid if containerized_deployment else 'ceph' }}"
    mode: "{{ ceph_directories_mode }}"
  with_items: "{{ rbd_client_admin_socket_path }}"

- name: get admin key from monitors
  command: "{{ container_exec_cmd }} ceph --cluster {{ cluster }} auth get client.admin"
  register: _rgw_admin_key
  delegate_to: "{{ groups.get(mon_group_name)[0] }}"
  run_once: true
  when:
    - cephx | bool
    - copy_admin_key | bool

- name: copy ceph admin key if needed
  copy:
    dest: "/etc/ceph/{{ cluster }}.client.admin.keyring"
    content: "{{ _rgw_admin_key.stdout + '\n' }}"
    owner: "{{ ceph_uid if containerized_deployment else 'ceph' }}"
    group: "{{ ceph_uid if containerized_deployment else 'ceph' }}"
    mode: "{{ ceph_keyring_permissions }}"
  when:
    - cephx | bool
    - copy_admin_key | bool

- name: copy SSL certificate & key data to certificate path
  copy:
    content: "{{ radosgw_frontend_ssl_certificate_data }}"
    dest: "{{ radosgw_frontend_ssl_certificate }}"
    owner: "{{ ceph_uid if containerized_deployment else 'ceph' }}"
    group: "{{ ceph_uid if containerized_deployment else 'ceph' }}"
    mode: 0440
  when: radosgw_frontend_ssl_certificate | length > 0 and radosgw_frontend_ssl_certificate_data | length > 0
  notify: restart ceph rgws
